### ISSUE TITLE
Lazy decryption

### ISSUE THREAD

**Issue by vnazarenko** [jmazzi/crypt_keeper#108]
Hi, i use crypt_keeper and it's really cool, but notice a big amount of 
   (0.2ms)  SELECT AES_DECRYPT([FILTERED])
   (0.4ms)  SELECT AES_DECRYPT([FILTERED])
   (0.2ms)  SELECT AES_DECRYPT([FILTERED])
   (0.2ms)  SELECT AES_DECRYPT([FILTERED])
Requests, as i understand it's for decryption of loaded records, is there any possibility to make keeper more lazy, for example to do request only when i try to access to encrypted data, because usually i do not need that secret stuff

**Comment by jmazzi** [comment]
Hi @vnazarenko, thanks for the report. The issue you are seeing is not caused by `crypt_keeper` directly. Internally, `crypt_keeper` uses rails [serialize](https://github.com/jmazzi/crypt_keeper/blob/bafbedde6f9d0051e1c8e30dae2b4139f78c87f6/lib/crypt_keeper/model.rb#L71) to handle the encryption and decryption of data. Rails serializers always call load when records are queried. This is the most recent version of `rails`. What version are you using?

**Comment by vnazarenko** [comment]
4.2.4

**Comment by yard** [comment]
same issue here. any flag to supress this behavior?

**Comment by tfwright** [comment]
There is an experimental PR open with more information about this issue. It attempts to mitigate this issue by switching away from serializers: 

https://github.com/jmazzi/crypt_keeper/pull/119

**Comment by jmazzi** [comment]
CryptKeeper uses serializers and serializers are now in Rails 5+.
