### ISSUE TITLE
Always updating crypt_keeper field

### ISSUE THREAD

**Issue by istvanfazakas** [jmazzi/crypt_keeper#123]
Hi,

I am using crypt keeper with devise on a user model, and I'm encrypting the users email address. The issue is, that even though I don't update the email field (only some other field), the email address field is updated every time. This is causing devise to send out confirmation emails every time I update the user. Is there a way to stop updating these field when they are not changed?

**Comment by itspriddle** [comment]
This is not possible right now due to how Rails serializers work on 4.2 and 5.0. There is more info in #108 and #119, but the gist is that in Rails, any serialized columns are always considered dirty by design.

Encrypting an email for login seems overkill to me. It is not something we have done on any of our apps using CryptKeeper. But if you need to do it for some reason, I would look into overriding the logic in Devise to send the confirmation emails in a different way than just checking for `email_changed?`.

**Comment by istvanfazakas** [comment]
Thank you. I already fixed it that way
