### ISSUE TITLE
Add support for Rails 5

### ISSUE THREAD

**Issue by cdussud** [jmazzi/crypt_keeper#134]
The readme says that Cryptkeeper 0.23 supports Rails 5, but there's no such version available and 0.22 only supports ActiveRecord 4.2.

**Comment by safetymonkey** [comment]
You can get around this by having the gem pull directly from this repo. I have crypt_keeper running on a Rails 5.0.2 app.

`gem 'crypt_keeper', github: 'jmazzi/crypt_keeper'`

**Comment by jesperronn** [comment]
Whats holding back a new release? I see a prerelease is ready:

https://github.com/jmazzi/crypt_keeper/releases/tag/v1.0.0.beta1

Rails 5 support is definitely relevant, and I think its a good call to bump the major version and follow Semver and go for 1.0.0, since the coming release will only support Rails 4 + Rails 5

Please call for help, if you need assistance with the release :)

**Comment by jmazzi** [comment]
@jesperronn 1.0.0 is live now

**Comment by jmazzi** [comment]
@cdussud @jesperronn 1.0.0 is live now

**Comment by jesperronn** [comment]
👍👏
