### ISSUE TITLE
Using on serialized fields?

### ISSUE THREAD

**Issue by systemnate** [jmazzi/crypt_keeper#156]
Is there any way to use `crypt_keeper` on serialized fields?  I noticed that it is not encrypting my serialized fields.

I created a sample app to demonstrate this: https://github.com/systemnate/crypt_keeper_serialize

But essentially, in my model, I have:

```
class Test < ApplicationRecord
  crypt_keeper :field1, :field2, encryptor: :postgres_pgp, key: 'super_good_password', salt: 'salt'
  serialize :field2
end
```

And when I do something like `Test.create(field1: 'test', field2: { test: 'test' })` and then look in the database, `field2` is stored in its normal `YAML` format.

Any ideas on how I could handle this?  Thanks in advance!

**Comment by itspriddle** [comment]
This isn't possible out of the box since CryptKeeper also uses `serialize` and ActiveRecord seems to only allow one `serialize` coder per-attribute and will use the last one called – in your example that makes `:field2` serialize with the default YAML coder.

If your main goal is to cut down on the number of `SELECT pgp_sym_{en,de}crypt` queries, I would recommend introducing a separate model like `EncryptedFields`, and then `Test.has_many :encrypted_fields` or similar. Then you can load them only when necessary. 

If you're keen on using a YAML serialized hash, you could implement a custom encryptor however. Something like this _ought_ to work:

```ruby
module CryptKeeper
  module Provider
    class PostgresPgpHash < PostgresPgp
      def dump(value)
        if value.blank? || CryptKeeper.stub_encryption?
          value
        else
          encrypt(value)
        end
      end

      def encrypt(value)
        rescue_invalid_statement do
          escape_and_execute_sql(["SELECT pgp_sym_encrypt(?, ?, ?)",
            YAML.dump(value), key, pgcrypto_options])['pgp_sym_encrypt']
        end
      end

      def decrypt(value)
        rescue_invalid_statement do
          if encrypted?(value)
            YAML.load escape_and_execute_sql(["SELECT pgp_sym_decrypt(?, ?)",
              value, key])['pgp_sym_decrypt']
          else
            value
          end
        end
      end
    end
  end
end
```

And in your model:

```ruby
class Test < ApplicationRecord
  crypt_keeper :field2, encryptor: :postgres_pgp_hash, key: "KEY", salt: "SALT"
end
```

Note if you rely on CryptKeeper's `search` methods, you would also need to implement `PostgresPgpHash#search` in a way that worked for your needs.

**Comment by systemnate** [comment]
Thanks for the detailed response.  I'll see what I can do!
