### ISSUE TITLE
ActiveRecord send indavlid data to database using PostgresPgp with binary column type

### ISSUE THREAD

**Issue by Arimeka** [jmazzi/crypt_keeper#177]
Looks like ActiveRecord automatically(?) [escape bytea](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb#L9) from model before sending data to database. So, `pgp_sym_encrypt` already return escaped bytea, and before sending ActiveRecord again escape data.

Decryption will work, because ActiveRecord automatically(?) unescape data, but it's really pain working with such data in other languages.

Oh, and `search_by_plaintext` not working with bytea type.

**Comment by joel** [comment]
This is indeed quite terrible, because this means we can't use the postgres function `PGP_SYM_ENCRYPT`/`PGP_SYM_DECRYPT` directly on the database, hence doing any operation on encrypted data and that why 

``` 
Model.search_by_plaintext(:field, 'searchstring')
``` 

will never work.

Indeed 

`bundle exec rails console`

```
enc = User.send :encryptor
r1 = ActiveRecord::Base.connection.execute('SELECT first_name FROM users')[0]
r2 = ActiveRecord::Base.connection.unescape_bytea(r1['first_name'])
enc.load(r2)
=> "Joel"
```

otherwise 

```
enc.load(r1['first_name'])
=> "\\x5c78633330643034303930333032346538646661376366313930313832373665643233613031303964363662653764666331303737353134636535353266613861386264323339313039653130643239333836646466376532303235336662333366383035613133653963656561666432323065326637356338653434383063663332666231666235393834613130373930343935306465"
```

and in `psql` console is fail

```
SELECT id, PGP_SYM_DECRYPT(first_name::bytea, 'AES_KEY') FROM users;
ERROR:  Wrong key or corrupt data
```

**Comment by stas** [comment]
I spent some time debugging this and the short answer here is to
 1. clearly state and remove support for binary columns for the `postgres_pgp` provider
 2. write a separate provider which calls binary-specific SQL functions to provide the encryption which call `unescape_bytea` after every `pgp_sym_encrypt_bytea` and `(un)escape_bytea` before/after every `pgp_sym_decrypt_bytea`.

Long story...

Before anything else, it is important to note that there are two types to represent the binary data in postgres: `hex` and `escaped`.

The `pg` gem will always return the escaped format of the `bytea` column.
The way it operates, is by calling [escape_bytea](https://www.rubydoc.info/gems/pg/PG/Connection#escape_bytea-class_method) and [unescape_bytea](https://www.rubydoc.info/gems/pg/PG/Connection#unescape_bytea-instance_method).

Which is ultimately the main reason why we have this issue in the first place.

Moving on to Rails, it will always try to make sure that the binary data is represented in the text form (the escaped format). This is why, if you run `psql(1)` it will always return a different value, which is the hex format. This is why running the encryption calls over the plain text values and not the table column values worked.

Now when saving the data, we'd save it in the same encrypted and escaped format, while we should be saving it in the encrypted and unescaped format (and let the database handle the final operation on how the data should be stored internally). This final step is important to allow running the encryption functions over the table column values.

Another issue here is the use of non-binary encryption functions to decrypt binary data. [Pgcrypto Docs](https://www.postgresql.org/docs/9.0/pgcrypto.html#AEN129675) clearly state:
> Decrypting bytea data with pgp_sym_decrypt is disallowed. This is to avoid outputting invalid character data. Decrypting originally textual data with pgp_sym_decrypt_bytea is fine.

I wrote a separate provider/serializer to handle the binary encryption support and I'll try to release it as soon as I finish reviewing all the concerns (some of which I discovered while working on this issue).

**Comment by stas** [comment]
I decided to _fork_ the implementation and place it into a separate gem, the relevant parts can be found here:
https://github.com/stas/active_record_pgcrypto/blob/master/lib/active_record/pgcrypto/symmetric_coder.rb#L34-L70

@jmazzi, thank you for your work, but I there are a couple of concerns that stopped me from contributing back, and particularly:
 * there are mixed implementations of binary and non-binary encryption calls which would require refactoring and separating all the pgcrypto coders; as I already mentioned, since there's no proper support for binary types, you should drop any support/notes asap or the users will end up with data that can be decrypted exclusively by your implementation
 * the use of raw SQL calls is broken and super custom, If we want to use the Arel API, it would require rewriting all the SQL-related integration
 * there are no integration tests for searching through the columns, I'd have to provide it for all the databases and implementations

I still don't know what's the easiest way to avoid migrating the whole table dataset due to this issue. :disappointed:
