### ISSUE TITLE
Different key per record

### ISSUE THREAD

**Issue by shinnc** [jmazzi/crypt_keeper#65]
Is it possible to have different key per record?

**Comment by nesrual** [comment]
Sorry about bumping a closed topic, however the above code will return a Proc object and not the actual key.

You would need to do something like:

    crypt_keeper :field, encryptor: :aes, key: (Proc.new { |record| record.key }).call(self)

Inspecting the `field`with `field.crypt_keeper_options` will give you something similar to:

    2.2.2 :005 > field.crypt_keeper_options
     => {:key=>#<Proc:0x007fcf8a8b0900@/some/path/to/your/code/...>} 

instead of the expected key.

More info here: http://awaxman11.github.io/blog/2013/08/05/what-is-the-difference-between-a-block/

**Comment by bsutherland** [comment]
I notice this feature doesn't work for `:aes_new`. I started looking into the code to see if I could monkey patch it in, but it doesn't seem straightforward given the way the code is factored now.

This feature is very important to us. If you'd consider adding it back in, we'd really appreciate it!

Until then, is there a workaround I could use to support different keys per record?

**Comment by bsutherland** [comment]
I looked at it some more, and I'm completely stuck. Because crypt_keeper assigns an encrypting serializer per model class attribute using `serialize`, I can't see a way to plugin in a callback which takes a record instance as a parameter. Please Help :smile:
