### ISSUE TITLE
Form fields display encrypted string in Rails 4.2

### ISSUE THREAD

**Issue by elcasu** [jmazzi/crypt_keeper#99]
Hi,
Im having an extrange issue when trying to edit an encrypted field through a form.
Everything works just fine, the data is saved ok and retreived without problems (if I print object.inspect, that field shows un-encrypted), but when I try to show the input with:

``<%= f.text_area :protected_field, class: "input-xxlarge text-field-box" %>``

The textarea contains the data encrypted.

Everything works fine in Rails 4.1.4. I'm having this issue only with Rails 4.2.1

**Comment by jmazzi** [comment]
@elcasu does the problem exist in rails 4.2.0? Are you able to create a small example app demonstrating the issue?

**Comment by elcasu** [comment]
@jmazzi yes, I just created a basic example here:

https://github.com/elcasu/CriptKeeperDemo

You can see you're able to create a new "demo" and list it's fields, but when you try to edit one, the crypted field contains encrypted data.

I'm using Rails 4.2.0 here

**Comment by jmazzi** [comment]
Apparently this intentional behavior by [rails](https://github.com/rails/rails/commit/d8e710410ea300ec4626250c0b35946cb52bc38c), it's using the `_before_type_cast` value. `crypt_keeper` uses `serialize` to handle the encryption so this is not a crypt_keeper issue, it's a rails serialize issue. Here is an [issue] someone else reported that is similar.

I would suggest filing a report

**Comment by jmazzi** [comment]
@elcasu apparently this intentional behavior by [rails](https://github.com/rails/rails/commit/d8e710410ea300ec4626250c0b35946cb52bc38c), it's using the `_before_type_cast` value. `crypt_keeper` uses `serialize` to handle the encryption so this is not a crypt_keeper issue, it's a rails serialize issue. Here is an issue rails/rails#16627 someone else reported that is similar.

Here is a simple way to show this is a rails issue. Change your model to the following in your demo app (delete the old demo records first). 

```ruby
class Demo < ActiveRecord::Base
  serialize :secret_value
end
```

When you create the record and then edit it, you will see the form field has the raw serialized value instead of the decoded value. I would suggest filing a report with Rails about it, as this is not a crypt_keeper problem.

**Comment by Kukunin** [comment]
The rails issue https://github.com/rails/rails/issues/16627 is closed and won't be fixed. So, you guys need to do the workaround: override `_before_type_cast` for encrypted fields to show decrypted value as well.
